import Head from "next/head";
import Link from "next/link";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";

const index: React.FC = () => {
  const { t } = useTranslation();
  return (
    <>
      <div className="w-full">
        <Head>
          <title>H2Grow | Home</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <main className="flex items-center w-[100%] justify-center p-8 flex-col text-white h-[calc(100vh-200px)]">
          <h1 className="text-6xl drop-shadow-default">{t("general.accountCreated")}</h1>
          <p className="text-xl mt-4 drop-shadow-default flex flex-row gap-4 items-center">
              <Link href="/login" className="flex items-center px-3 py-2 bg-primary-green hover:bg-secondary-green transition-all text-white rounded-sm drop-shadow-default">
                {t("general.login")}
              </Link>
              {t("home.loginOrRegister")}
          </p>
        </main>
      </div>
    </>
  );
};

export const getServerSideProps = async (context: { locale: any }) => {
  const { locale } = context;

  return {
    props: {
      ...(await serverSideTranslations(locale ?? "en", ["common"])),
    },
  };
};

export default index;
