name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    environment: DOCKERHUB_TOKEN

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
          cd frontend
          docker build -t woutpaepenucll/h2grow-frontend .
          docker ps
    - name: Login to Docker Hub and push
      env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
            docker login  -u woutpaepenucll -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker push woutpaepenucll/h2grow-frontend:latest
      

    # - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag h2grow-frontend:$(date +%s)
